articles/api/urls.py
from django.conf.urls import url, include

from articles.api.views import *

from rest_framework.routers import SimpleRouter


router = SimpleRouter()
router.register(r'articles', ArticlesViewSet)

urlpatterns = [
    url(r'api/v1/', include(router.urls)),
]

articles/urls.py
from django.urls import path
from django.conf.urls import url, include
from articles.views import *

app_name = 'articles'
urlpatterns = [
    path('articles', ArticleListView.as_view(), name='articles-list'),
    path('articles/new/', ArticleCreateView.as_view(), name='article-new'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article-update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article-show'),
    url(r'^', include('articles.api.urls')),
]

orders_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from orders.views import make_order, save_order, orders_report
from catalogs.views import *

from rest_framework.routers import SimpleRouter

from orders.views import OrdersViewSet, dashboard, OrderPDF

router = SimpleRouter()
router.register(r'orders', OrdersViewSet)

urlpatterns = [
    path(r'', make_order),
    path('admin/', admin.site.urls),
    url(r'^make_order$', make_order, name = 'make_order'),
    url(r'^save_order$', save_order, name = 'save_order'),
    url(r'^orders_report$', orders_report, name = 'orders_report'),
    url(r'^dashboard$', dashboard, name = 'dashboard'),
    url(r'^pdf_order/(?P<order_id>\d+)/type/(?P<order_type_id>\d+)$', OrderPDF.as_view(), name="order_pdf"),
    url(r'^', include('articles.urls', namespace='articles')),
    url(r'^', include('catalogs.urls', namespace='catalogs')),
    url(r'^', include('vendors.urls', namespace='vendors')),
    url(r'api/v1/', include(router.urls)),
]

vendors/urls.py
from django.urls import path
from django.conf.urls import url, include
from vendors.views import *

app_name = 'vendors'
urlpatterns = [
    path('vendors', VendorListView.as_view(), name='vendors-list'),
    path('vendors/new/', VendorCreateView.as_view(), name='vendor-new'),
    path('vendor/<int:pk>/update/', VendorUpdateView.as_view(), name='vendor-update'),
    path('vendor/<int:pk>/delete/', VendorDeleteView.as_view(), name='vendor-delete'),
    path('vendor/<int:pk>/', VendorDetailView.as_view(), name='vendor-show'),
    url(r'^', include('vendors.api.urls')),
]

articles/models.py
from django.db import models

from vendors.models import Vendor

from django.urls import reverse

from django.core.validators import *

# Create your models here.
class Article(models.Model):
	id = models.AutoField(primary_key = True)
	code = models.CharField(max_length = 10)
	description = models.TextField(null = True)
	vendors = models.ManyToManyField(Vendor)
	price = models.DecimalField(decimal_places = 4, max_digits = 12, validators=[MinValueValidator(0)])

	def __str__(self):
		return "%s  -  %s" % (self.code, self.description)

	def get_absolute_url(self):
	        return reverse('articles:article-show', kwargs={'pk': self.pk})

articles/forms.py
from django.forms import ModelForm

from .models import Article 
class ArticleForm(ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['vendors'].required = False

	class Meta:
		model = Article
		exclude = []

articles/api/views.py
from .serializers import *
from rest_framework import viewsets

from articles.models import Article
# Create your views here.
class ArticlesViewSet(viewsets.ModelViewSet):
	queryset = Article.objects.all()
	serializer_class = ArticleSerializer

articles/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from rest_framework import viewsets
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import ArticleForm
from .models import *

class ArticleListView(ListView):
    model = Article

class ArticleDetailView(DetailView):
    model = Article

class ArticleCreateView(CreateView):
	model = Article
	#fields = ['code', 'description', 'price']
	form_class = ArticleForm
	

class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name_suffix = '_update_form'

class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('articles:articles-list')

articles/templates/articles/article_confirm_delete.html
{% extends 'base.html' %}

{% block contenido %}
	<h1>Delete Article</h1>

	<p>Are you sure you want to delete the article: {{ article }}?</p>

	<p>
		<a href="{% url 'articles:articles-list' %}" class="btn btn-success btn-lg">Return to articles list</a> | <a href="{% url 'articles:article-show' article.pk %}" class="btn btn-success btn-lg">Show article details</a> 
	</p>
	<form action="" method="POST">
	  {% csrf_token %}
	  <input class="btn btn-sm btn-danger" type="submit" value="Yes, delete.">
	</form>
	
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block contenido %}
	<div class="row">
		<div class="col-sm-12 col-md-8 offset-md-2">
		    <div class="row">
		    	<div class="col-sm-10 col-md-8">
					<h1>Detalles del artículo</h1>
		    	</div>
		    	<div class="col-sm-2 col-md-4">

					<a href="{% url 'articles:article-update' article.pk %}" class="btn btn-info float-end">Editar</a>    		
		    	</div>
		    </div>
			<hr>
			<p>
				<span><b>Code:</b></span>
				{{article.code}}
			</p>
			<p>
				<span><b>Description:</b></span>
				{{article.description}}
			</p>
			<p>
				<span><b>Price:</b></span>
				{{article.price}}
			</p>
			<p>
				<div><b>Vendors</b></div>
				<ul>
					{% if article.vendors.count %}
						{% for vendor in article.vendors.all %}
							<li>{{ vendor.name }}</li>
						{% endfor%}
					{% else %}
						<li>Without Vendors</li>
					{% endif %}
				</ul>
			</p>
		</div>
	</div>


{% endblock %}

articles/templates/articles/article_form.html
{% extends 'base.html' %}

{% block contenido %}
	{% include 'articles/form.html' with type="create" %}
{% endblock %}

{% block scripts_js %}
	<script>
		$('form input, form textarea, form select').addClass('form-control');
		$('form input[type="submit"]').addClass('btn btn-success');
		$('form select').required(false);
	</script>
{% endblock scripts_js %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}

{% block contenido %}
	<h1>Listado de artículos</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Code</th>
				<th>Description</th>
				<th>Price</th>
				<th>Details</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			{% for article in object_list %}
				<tr>
					<td>{{ article.pk }}</td>
					<td>{{article.code}}</td>
					<td>{{article.description}}</td>
					<td>{{article.price}}</td>
					<td> <a href="{% url 'articles:article-show' article.pk %}" class="btn-sm btn-warning">Details</a> </td>
					<td> <a href="{% url 'articles:article-update' article.pk %}" class="btn-sm btn btn-info">Update</a> </td>
					<td> <a href="{% url 'articles:article-delete' article.pk %}" class="btn-sm btn btn-danger">Delete</a> </td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

articles/templates/articles/article_update_form.html
{% extends 'base.html' %}

{%block contenido%}	
{% include 'articles/form.html' with type="update" %}
{%endblock%}

{% block scripts_js %}
	<script>
		$('form input, form textarea, form select').addClass('form-control');
		$('form input[type="submit"]').addClass('btn btn-success');
	</script>
{% endblock scripts_js %}

articles/templates/articles/form.html
<div class="row">
		<div class="col-sm-12 col-md-6 offset-md-3">
			{% if type == 'create' %}
				<h1>Crear Artículo</h1>
			{% else %}
				<h1>Editar Artículo</h1>
			{% endif %}
			<form action="" method="POST">
			    {% csrf_token %}
			    {{ form }}
			    <input type="submit" value="Guardar">
			</form>
		</div>
	</div>