orders_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from orders.views import make_order, save_order, orders_report
from catalogs.views import *

from rest_framework.routers import SimpleRouter

from orders.views import OrdersViewSet, dashboard, OrderPDF

router = SimpleRouter()
router.register(r'orders', OrdersViewSet)

urlpatterns = [
    path(r'', make_order),
    path('admin/', admin.site.urls),
    url(r'^make_order$', make_order, name = 'make_order'),
    url(r'^save_order$', save_order, name = 'save_order'),
    url(r'^orders_report$', orders_report, name = 'orders_report'),
    url(r'^dashboard$', dashboard, name = 'dashboard'),
    url(r'^pdf_order/(?P<order_id>\d+)/type/(?P<order_type_id>\d+)$', OrderPDF.as_view(), name="order_pdf"),
    url(r'^', include('articles.urls', namespace='articles')),
    url(r'^', include('catalogs.urls', namespace='catalogs')),
    url(r'^', include('vendors.urls', namespace='vendors')),
    url(r'api/v1/', include(router.urls)),
]

vendors/api/urls.py
from django.conf.urls import url, include

from vendors.api.views import *

from rest_framework.routers import SimpleRouter


router = SimpleRouter()
router.register(r'vendors', VendorsViewSet)

urlpatterns = [
    url(r'api/v1/', include(router.urls)),
]

vendors/urls.py
from django.urls import path
from django.conf.urls import url, include
from vendors.views import *

app_name = 'vendors'
urlpatterns = [
    path('vendors', VendorListView.as_view(), name='vendors-list'),
    path('vendors/new/', VendorCreateView.as_view(), name='vendor-new'),
    path('vendor/<int:pk>/update/', VendorUpdateView.as_view(), name='vendor-update'),
    path('vendor/<int:pk>/delete/', VendorDeleteView.as_view(), name='vendor-delete'),
    path('vendor/<int:pk>/', VendorDetailView.as_view(), name='vendor-show'),
    url(r'^', include('vendors.api.urls')),
]

vendors/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Vendor(models.Model):
	id = models.AutoField(primary_key = True)
	name = models.CharField(max_length = 80)
	address = models.CharField(max_length = 120)
	articles = models.ManyToManyField('articles.Article', through='articles.article_vendors')

	def __str__(self):
		return self.name

	def get_absolute_url(self):
	        return reverse('vendors:vendor-show', kwargs={'pk': self.pk})

vendors/forms.py
from django.forms import ModelForm

from .models import Vendor 
class VendorForm(ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['articles'].required = False

	class Meta:
		model = Vendor
		exclude = []

vendors/api/views.py
from .serializers import *
from rest_framework import viewsets

from vendors.models import Vendor
# Create your views here.
class VendorsViewSet(viewsets.ModelViewSet):
	queryset = Vendor.objects.all()
	serializer_class = VendorSerializer

vendors/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import VendorForm
from .models import *

class VendorListView(ListView):
    model = Vendor

class VendorDetailView(DetailView):
    model = Vendor

class VendorCreateView(CreateView):
	model = Vendor
	#fields = ['code', 'description', 'price']
	form_class = VendorForm

class VendorUpdateView(UpdateView):
    model = Vendor
    form_class = VendorForm
    template_name_suffix = '_update_form'

class VendorDeleteView(DeleteView):
    model = Vendor
    success_url = reverse_lazy('vendors:vendors-list')

vendors/templates/vendors/form.html
<div class="row">
		<div class="col-sm-12 col-md-6 offset-md-3">
			{% if type == 'create' %}
				<h1>Crear Proveedor</h1>
			{% else %}
				<h1>Editar Proveedor</h1>
			{% endif %}
			<form action="" method="POST">
			    {% csrf_token %}
			    {{ form }}
			    <input type="submit" value="Guardar">
			</form>
		</div>
	</div>

vendors/templates/vendors/vendor_confirm_delete.html
{% extends 'base.html' %}

{% block contenido %}
	<h1>Delete Vendor</h1>

	<p>Are you sure you want to delete the vendor: {{ vendor }}?</p>

	<p>
		<a href="{% url 'vendors:vendors-list' %}" class="btn btn-success btn-lg">Return to vendors list</a> | <a href="{% url 'vendors:vendor-show' vendor.pk %}" class="btn btn-success btn-lg">Show vendor details</a> 
	</p>
	<form action="" method="POST">
	  {% csrf_token %}
	  <input class="btn btn-sm btn-danger" type="submit" value="Yes, delete.">
	</form>
	
{% endblock %}

vendors/templates/vendors/vendor_detail.html
{% extends 'base.html' %}

{% block contenido %}
	<div class="row">
		<div class="col-sm-12 col-md-8 offset-md-2">
		    <div class="row">
		    	<div class="col-sm-10 col-md-8">
					<h1>Detalles del Proveedor</h1>
		    	</div>
		    	<div class="col-sm-2 col-md-4">

					<a href="{% url 'vendors:vendor-update' vendor.pk %}" class="btn btn-info float-end">Editar</a>    		
		    	</div>
		    </div>
			<hr>
			<p>
				<span><b>name:</b></span>
				{{vendor.name}}
			</p>
			<p>
				<span><b>address:</b></span>
				{{vendor.address}}
			</p>
			
			<p>
				<div><b>Articles</b></div>
				<ul>
					{% if vendor.articles.count %}
						{% for article in vendor.articles.all %}
							<li>{{ article.code }} - {{ article.description }} </li>
						{% endfor%}
					{% else %}
						<li>Without Articles</li>
					{% endif %}
				</ul>
			</p>
		</div>
	</div>


{% endblock %}

vendors/templates/vendors/vendor_form.html
{% extends 'base.html' %}

{% block contenido %}
	{% include 'vendors/form.html' with type="create" %}
{% endblock %}

{% block scripts_js %}
	<script>
		$('form input, form textarea, form select').addClass('form-control');
		$('form input[type="submit"]').addClass('btn btn-success');
	</script>
{% endblock scripts_js %}

vendors/templates/vendors/vendor_list.html
{% extends 'base.html' %}

{% block contenido %}
	<h1>Listado de proveedores</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Address</th>
				<th>Details</th>
				<th>Update</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			{% for vendor in object_list %}
				<tr>
					<td>{{ vendor.pk }}</td>
					<td>{{vendor.name}}</td>
					<td>{{vendor.address}}</td>
					<td> <a href="{% url 'vendors:vendor-show' vendor.pk %}" class="btn-sm btn-warning">Details</a> </td>
					<td> <a href="{% url 'vendors:vendor-update' vendor.pk %}" class="btn-sm btn btn-info">Update</a> </td>
					<td> <a href="{% url 'vendors:vendor-delete' vendor.pk %}" class="btn-sm btn btn-danger">Delete</a> </td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

vendors/templates/vendors/vendor_update_form.html
{% extends 'base.html' %}

{%block contenido%}	
{% include 'vendors/form.html' with type="update" %}
{%endblock%}

{% block scripts_js %}
	<script>
		$('form input, form textarea, form select').addClass('form-control');
		$('form input[type="submit"]').addClass('btn btn-success');
	</script>
{% endblock scripts_js %}