articles/urls.py
from django.urls import path
from django.conf.urls import url, include
from articles.views import *

app_name = 'articles'
urlpatterns = [
    path('articles', ArticleListView.as_view(), name='articles-list'),
    path('articles/new/', ArticleCreateView.as_view(), name='article-new'),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name='article-update'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article-show'),
    url(r'^', include('articles.api.urls')),
]

orders_management/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from orders.views import make_order, save_order, orders_report
from catalogs.views import *

from rest_framework.routers import SimpleRouter

from orders.views import OrdersViewSet, dashboard, OrderPDF

router = SimpleRouter()
router.register(r'orders', OrdersViewSet)

urlpatterns = [
    path(r'', make_order),
    path('admin/', admin.site.urls),
    url(r'^make_order$', make_order, name = 'make_order'),
    url(r'^save_order$', save_order, name = 'save_order'),
    url(r'^orders_report$', orders_report, name = 'orders_report'),
    url(r'^dashboard$', dashboard, name = 'dashboard'),
    url(r'^pdf_order/(?P<order_id>\d+)/type/(?P<order_type_id>\d+)$', OrderPDF.as_view(), name="order_pdf"),
    url(r'^', include('articles.urls', namespace='articles')),
    url(r'^', include('catalogs.urls', namespace='catalogs')),
    url(r'^', include('vendors.urls', namespace='vendors')),
    url(r'api/v1/', include(router.urls)),
]

vendors/urls.py
from django.urls import path
from django.conf.urls import url, include
from vendors.views import *

app_name = 'vendors'
urlpatterns = [
    path('vendors', VendorListView.as_view(), name='vendors-list'),
    path('vendors/new/', VendorCreateView.as_view(), name='vendor-new'),
    path('vendor/<int:pk>/update/', VendorUpdateView.as_view(), name='vendor-update'),
    path('vendor/<int:pk>/delete/', VendorDeleteView.as_view(), name='vendor-delete'),
    path('vendor/<int:pk>/', VendorDetailView.as_view(), name='vendor-show'),
    url(r'^', include('vendors.api.urls')),
]

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="es-MX">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% csrf_token %}
        
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        {% block scripts_css %} {% endblock scripts_css %}
        <style>
            body {
                background-color: #eee;
                padding-top: 50px;
            }
            .content{
                background-color: white;
                box-shadow: 2px 2px 6px rgba(0,0,0,0.4);
                padding: 10px;
                margin-top:5px;
            }

            {% block personal_styles %}{% endblock personal_styles %}
        </style>


        <!-- DevExtreme theme -->
        <link rel="stylesheet" href="https://cdn3.devexpress.com/jslib/21.1.4/css/dx.light.css">
     
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
        <!-- Default theme -->
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <style>
             #main-navbar{
                background: #555;
                height: 42px;
              }

              #main-navbar a {
                color: aliceblue;
                background: rgba(123, 123, 128, 0.15);
              }

              #main-navbar ul{
                margin-top: 0; 
              }

              #main-navbar ul li{
                color: aliceblue;
                list-style-type: none;
                display: inline-block;
                width: 180px;
                padding: 3px;
                margin: 7px 10px;
                text-align: center;
                max-height: 28px;
                background: rgba(123, 123, 128, 0.15);
              }
              #main-navbar ul li:hover{
                cursor: pointer;
                background: rgba(123, 123, 128, 1);
              }

              #main-navbar ul li#catalogs-menu-li{
                  list-style-type: none;
                  display: inline-block;
                  width: 180px;
                  padding: 3px;
                  margin: 7px 10px;
                  text-align: center;
                  max-height: 28px;
              }

              #catalogs-menu-li .dropdown-item{
                background: transparent;
                font-weight: 200px;
                color: #696957;
              }

              #catalogs-menu-li .dropdown-item:hover{
                background: transparent;
                border: 1px solid #111;
              }

              #catalogs-menu-li .dropdown-menu a{
                background: transparent;
              }
              
              #catalogs-menu-li .dropdown-menu li{
                background: transparent;
              }

              #catalogs-menu-li .dropdown-menu li:hover{
                background: transparent;
              }


              #print-btn{
                border: 1px solid #ccc;
                margin-bottom: 15px;
                margin-inline-start: 10px;
                max-width: 60px;
                cursor: pointer;
                vertical-align: -webkit-baseline-middle;
              }

              #print-btn:hover{
                border: 1px solid #aaa;
                max-width: 65px;
                color: red;
              }

              #errors-containerr{
                background: rgba(230, 230, 230, 0.4);
                padding: 5px 15px;
                box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
                color: #dc3b3b;
                margin-bottom: 10px;
                display: none;
              }

              .dropdown-item{
                background-color: transparent;
                border: 1px solid #ccc
              }

              .dropdown-item{
                background-color: transparent;
                border: 1px solid #ccc
              }
        </style>
         <nav id="main-navbar" style="margin-top: -46px;">
              <ul>
                <li>  <a href="{% url 'make_order' %}">Hacer Pedido</a>  </li>
                <li>  <a href="{% url 'orders_report' %}">Reporte de Ordenes</a>   </li>
                <li>  <a href="{% url 'articles:articles-list' %}">Artículos</a>   </li>
                <li>  <a href="{% url 'vendors:vendors-list' %}">Proveedores</a>   </li>

                <li id="catalogs-menu-li">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                      Catálogos
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                      <li><a class="dropdown-item" href="#">Tipo de clientes</a></li>
                      <li><a class="dropdown-item" href="#">Tipo de ordenes</a></li>
                      <li><a class="dropdown-item" href="#">Almacenes</a></li>
                    </ul>
                  </div>
                  
                </li>
              </ul>
            </nav>
        <div class="content">
            {% block contenido %}{% endblock contenido %}
        </div>
  
       {% include 'javascripts.html' %}

        {% block scripts_js %} {% endblock scripts_js %}
    </body>
</html>

templates/javascripts.html
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.6.0/jszip.min.js"></script>
<!-- DevExtreme library -->
<script type="text/javascript" src="https://cdn3.devexpress.com/jslib/21.1.4/js/dx.all.js"></script>

<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>


 <script>
    let articles = [];
    let instanceGridArticles = null;
    let articlesDS;
    let validator_warehouse, validator_sucursal, validator_associatedCompany;
    let errors_json;
    
        $.get('/api/v1/orders/?urgent=True&order_type_id=1&deliver_date__isnull=True&customer__tipo_cliente_id=4').then(function(resp){
            let data = resp;
           
            $("#buttonContainer").dxDataGrid({
                columns: [{dataField: 'order_number', alignment:'center'}, {dataField: 'order_type',  caption: 'Type', alignment: 'center'}, 'customer', {dataField: 'created_date', alignment: 'center'}, {dataField: 'deliver_date', alignment: 'center'}, {dataField:'urgent', allowSort: true, sortOrder: 'desc'}, {dataField: 'num_articles', caption: 'Num. artículos', alignment: 'center', width: '100px'}],
                noDataText: 'Sin ordenes',
                dataSource: data,
                showBorders: true,
                columnAutoWidth: true,
                filterRow: {visible: true},
                grouping:{ texts:{ groupContinuesMessage: "Continúa en la página siguiente" }},
                groupPanel: {visible: true, emptyPanelText: "Arrastre aquí la columna para agrupar"},
                export: {enabled: true, fileName: 'orders_report', allowExportSelectedData: true, 
                    excelFilterEnabled: true, excelWrapTextEnabled: true, texts: {exportAll: 'Exportar Todo', exportSelectedRows: 'Exportar Selección'}}
            });
          
        }, function(error){
            alert('Error al cargar las ordenes');
        });

        $.get('/api/v1/articles').then(
            resp => {
                articles = resp;
                articlesDS = new DevExpress.data.DataSource({store: articles});
                $('#grid-articulos').dxDataGrid({noDataText: 'Sin artículos',
                                                filterRow: {visible: true},
                                                height: '225px',
                                                dataSource: articlesDS,
                                                paging: {enabled: false},
                                                columns: ['code',
                                                'description',
                                                {dataField:'price',
                                                format: {type: 'fixedPoint',
                                                precision: 2},
                                                dataType: 'number'},
                                                {caption: 'Add',
                                                alignment: 'center',
                                                cellTemplate: function(cont, ops){
                                                    cont.append(`<div class='btn btn-outline-dark btn-sm' onclick="add_article_to_order(${ops.data.id}, '${ops.data.code}', '${ops.data.description}', ${ops.data.price});">+</div>`);} }], 
                                                onRowDblClick: (elem)=> add_article_to_order(elem.data.id, elem.data.code, elem.data.description, elem.data.price)});
                instanceGridArticles = $('#grid-articulos').dxDataGrid('instance');
            }, error => {
                alert('error al buscar artículos');
            }
        );

        validator_warehouse = $('#detail-warehouse-container').dxValidationGroup({});
        validator_sucursal = $('#detail-sucursal-container').dxValidationGroup({});
        validator_associatedCompany = $('#detail-associatedcompany-container').dxValidationGroup({});

        $.get('/api/v1/warehouses').then(resp=> {
            $('#cmb-warehouses').dxLookup({ dataSource: resp,
                                            displayExpr: 'code',
                                            valueExpr: 'id',
                                            placeholder: 'Seleccione el almacen',
                                            title: 'Warehouse',
                                            name: 'warehouse',
                                            showCancelButton: false,
                                            showPopupTitle: false,
                                            stylingMode: 'filled',
                                            animation: {show: {
                                                type: 'pop',
                                                duration: 250
                                            }}
                                         })
                                .dxValidator({validationRules: [
                                                {type: 'required',
                                                message: 'Field Required'}],
                                              validationGroup: validator_warehouse});


        });

        $('#reference-input').dxTextBox({name: 'reference', 
                                        placeholder: 'Introduzca la referenia. Ej: OU008236-CH03'})
                             .dxValidator({validationRules: [
                                                {type: 'required', 
                                                message: 'Field Required'}], 
                                           validationGroup: validator_sucursal});

        $('#sucursal-code-input').dxTextBox({name: 'sucursal_code',
                                             placeholder: 'Introduzca el código de la sucursal'})
                                 .dxValidator({validationRules: [{type: 'required', 
                                                                  message:'Sucursal Code Required'}], 
                                              validationGroup: validator_sucursal});

        $('#reference-associated-input').dxTextBox({name: 'reference_ac',
                                                    placeholder: 'Ej, OU51214-CH03'})
                                        .dxValidator({validationRules: [{type: 'required',
                                                                        message:'Member Code Required'}], 
                                                    validationGroup: validator_associatedCompany});


        $('#member-code-input').dxTextBox({name: 'member_code',
                                           placeholder: 'Introduzca el código del socio'})
                                .dxValidator({validationRules: [{type: 'required', 
                                                                message:'Member Code Required'}], 
                                            validationGroup: validator_associatedCompany});


        let order_articles = [];

        function add_article_to_order(article_id, code, desc, price) {
            let quantity;

            alertify.prompt( 'Artículos a agregar', '', 
                function(evt, value) { 
                    let index;
                    quantity = value;
                    if(parseInt(quantity) > 0){
                        $('#articles-order-table tbody').append(`<tr>\
                            <td>${code}</td> \
                            <td>${desc}</td> \
                            <td>${quantity}</td> \
                            <td>${price}</td> \
                            <td>${quantity*price}</td> \
                        </tr>`);
                        let total_elem = $('#total-container #total-value');
                        total_elem.html((parseFloat(total_elem.html()) + quantity*price).toFixed(2));
                        order_articles.push({article_id: article_id, quantity: quantity});
                        articles.find((elem, i)=>{index = i; if(elem.id == article_id){ return true;}  });
                        articles.splice(index, 1);
                        instanceGridArticles.refresh();

                    }else if(quantity != null){
                        alert('No es una cantidad valida');
                    }
                }
            );
        }

        function check_order_type(selection){
            switch(parseInt(selection.value)){
                case 1: $('#detail-warehouse-container').css('display', 'block');
                        $('#detail-sucursal-container').css('display', 'none');
                        $('#detail-associatedcompany-container').css('display', 'none');
                    break;
                case 2: $('#detail-sucursal-container').css('display', 'block'); 
                        $('#detail-warehouse-container').css('display', 'none');
                        $('#detail-associatedcompany-container').css('display', 'none');
                    break;
                case 3: $('#detail-associatedcompany-container').css('display', 'block'); 
                        $('#detail-sucursal-container').css('display', 'none');
                        $('#detail-warehouse-container').css('display', 'none');
                    break;
            }
        }

        function articlesAdded(){
            if(order_articles.length == 0){
                alertify.error('No ha agregado artículos');
                return false
            };
            return true;
        }
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        function save_order(){
            //let order_type_id = parseInt($('input[name=order_type]:checked')[0].value());
            //alert(order_articles);
            
            let order_type_id = parseInt($('input[name=order_type]:checked')[0].value);
            let validator;
            switch(order_type_id){
                //Distribution Center
                case 1: validator = validator_warehouse;
                    break;
                //Sucursal
                case 2: validator = validator_sucursal;
                    break;
                //Associated Company
                case 3: validator = validator_associatedCompany;
                    break;
                default: alertify.error('Tipo de orden invalido');
                    return;
            }

            if(DevExpress.validationEngine.validateGroup(validator).isValid && articlesAdded()){
                 data = { 
                       articles: JSON.stringify(order_articles),
                       order_type_id: order_type_id,
                       urgent: $('input[name=urgent]').is(':checked'),
                       csrfmiddlewaretoken: csrftoken
                   };

                  //ALMACEN
                 if(parseInt($('input[name=order_type]:checked')[0].value) == 1){
                       data.warehouse_id = parseInt($('input[name=warehouse]')[0].value);
                 }
                 if(parseInt($('input[name=order_type]:checked')[0].value) == 2 ){
                       data.reference = $('input[name=reference]')[0].value;
                       data.sucursal_code = $('input[name=sucursal_code]')[0].value;
                 }
                 if(parseInt($('input[name=order_type]:checked')[0].value) == 3  ){
                       data.reference =  $('input[name=reference_ac]')[0].value;
                       data.partner_code = $('input[name=member_code]')[0].value;
                 }

                 $.post('/save_order', data).then(resp => {
                    $('#errors-containerr').html('');
                    $('#errors-containerr').hide('fast');
                    DevExpress.ui.notify('Orden guardada. No. Orden: ' + resp.
                        order_number, 'success');
                    $('#order-number-value').html(resp.order_number);
                    $('#order-number-container').css('display', 'block');
                    $('#btn-make-order').hide('slow');
                 }, error => {
                    let errors_html_str = "<strong style=\"color: #484646;\" >Errors list</strong><hr style=\"margin: 0;\"/>";
                    let errors_containter = $('#errors-containerr');
                    for(let field of Object.keys(error.responseJSON)){
                        errors_html_str += `<div> <b>${field}</b> <ul>`;
                        for(let e of error.responseJSON[field]){
                            errors_html_str += `<li>${e}</li>`;
                        }
                        errors_html_str += '</ul></div>';
                    }

                    errors_containter.show('fast');
                    errors_containter.html(errors_html_str);
                    console.error('Error al guardar la orden. ' + error);
                    alertify.error('Error al guardar');
                 });
            }
        } 

        function print_order(){
            let [order_id, order_type_id] = [$('#order-number-value').html(),
                                            $('input[name=order_type]:checked')[0].value];
            window.open(`/pdf_order/${order_id}/type/${order_type_id}`, 
                        "_blank", '');
        }          

</script>